defaults :
  - modulus_default
  - arch:
      - fully_connected
  - optimizer : adam
  - scheduler : tf_exponential_lr
  - loss : sum
  - _self_

jit : false
scheduler : 
  decay_rate : 0.95
  decay_steps : 4000

network_dir : "network_checkpoint"
initialization_network_dir : ""
save_filetypes : "vtk,npz"

optimizer: 
  lr : 1e-4

training:
  rec_validation_freq: 1000
  rec_inference_freq: 1000
  rec_monitor_freq: 1000
  rec_constraint_freq: 1000
  max_steps : 1000000

