defaults:
  - modulus_default
  - scheduler: tf_exponential_lr
  - optimizer: adam
  - loss: sum
  - _self_

scheduler: 
  decay_rate: 0.95
  decay_steps: 15000            

optimizer: 
  lr: 1e-3                      

training:
  rec_validation_freq: 5000
  rec_inference_freq: 5000
  rec_monitor_freq: 1000
  rec_constraint_freq: 2000
  max_steps: 1500000             

jit: true               # Set jit to false if you receive memory errors when using "parameterized: true"

custom:
  arch: "FourierNetArch"
  parameterized: false

network_dir: "network_checkpoint_flow"
initialization_network_dir: ""
save_filetypes: "vtk"

batch_size:
  inlet: 560
  outlet: 560
  no_slip: 20000
  lr_interior: 2500
  hr_interior: 2500
  integral_continuity: 11250
  num_integral_continuity: 5

graph:
  func_arch: true
