defaults :
  - modulus_default
  - arch:
      - fully_connected
  - scheduler: tf_exponential_lr
  - optimizer: adam
  - loss: sum
  - override training: variational_training
  - _self_

cuda_graphs: False

scheduler:
  decay_rate: 0.95
  decay_steps: 10000

training:
  rec_results_freq: 1000
  rec_constraint_freq: 10000
  max_steps : 1000000

batch_size:
  top: 256
  bottom: 512
  interior: 8192