defaults :
  - modulus_default
  - scheduler: tf_exponential_lr
  - optimizer: adam
  - loss: sum
  - _self_

cuda_graphs: false
jit: false

custom:
  gradient_method: fdm
  ntrain: 1998
  nval: 1
  ntest: 1


 
network_dir : "ResSim"

  
scheduler:
  decay_rate: 0.95
  decay_steps: 1000
  
optimizer:
    weight_decay: 1e-4
    lr: 1e-3

training:
  rec_results_freq : 10000
  max_steps : 200000
  rec_constraint_freq: 10000 

loss:
  weights:
    pressure: 1.0
    pressured: 1e-1
    water_sat: 1.0
    saturationd: 1e-1    

batch_size:
  grid: 1
  validation: 1
  test: 1
