defaults :
  - modulus_default
  - arch:
      - fully_connected
  - scheduler: tf_exponential_lr
  - optimizer: adam
  - loss: sum
  - _self_

cuda_graphs: false
find_unused_parameters: true

scheduler:
  decay_rate: 0.95
  decay_steps: 1500

training:
  rec_results_freq: 1000
  rec_constraint_freq: 10000
  max_steps : 50000

batch_size:
  surface: 1024
