defaults:
  - modulus_default
  - scheduler: tf_exponential_lr
  - optimizer: adam
  - loss: sum
  - _self_

scheduler: 
  decay_rate: 0.95
  decay_steps: 8000             

optimizer:
  lr: 1e-3                      

training:
  rec_validation_freq: 5000
  rec_inference_freq: 5000
  rec_monitor_freq: 1000
  rec_constraint_freq: 2000
  max_steps: 800000             

jit: true                       # Set jit to false if you receive memory errors when using "parameterized: true"

custom:
  arch: "FourierNetArch"
  parameterized: false
  
network_dir: "network_checkpoint_heat"
initialization_network_dir: "../fpga_flow/network_checkpoint_flow"
save_filetypes: "vtk"

batch_size:
  inlet: 560
  outlet: 560
  channel_walls: 10000 
  fluid_solid_interface: 10000  
  heat_source: 3200
  lr_flow_interior: 2500
  hr_flow_interior: 2500
  solid_interior: 3000
