defaults :
  - modulus_default
  - arch:
      - fourier
  - scheduler: tf_exponential_lr
  - optimizer: adam
  - loss: sum
  - _self_

network_dir : "baseline"
# network_dir : "tl_0"  # for TL runs (change id for each run)
# initialization_network_dir : "../limerock_flow/baseline"  # for TL runs


scheduler:
  decay_rate: 0.95
  decay_steps: 10000
  # decay_steps: 2500  # for TL runs

training:
  rec_results_freq : 1000
  rec_constraint_freq: 5000
  max_steps: 1000000
  # max_steps : 200000  # for TL runs

batch_size:
  inlet: 250
  outlet: 250
  no_slip: 12000
  lr_interior: 2450
  hr_interior: 3450
  integral_continuity: 8150
  num_integral_continuity: 8

