defaults :
  - modulus_default
  - arch:
      - fully_connected
  - scheduler: tf_exponential_lr
  - optimizer: adam
  - loss: sum
  - _self_

scheduler:
  decay_rate: 0.95
  decay_steps: 15000

training:
  rec_results_freq : 2000
  rec_constraint_freq: 10000
  max_steps : 2000000

batch_size:
  panel_left: 250
  panel_right: 250
  panel_bottom: 150
  panel_corner: 5
  panel_top: 150
  panel_window: 3500
  lr_interior: 7000
  hr_interior: 4000